FROM python:3.11-slim

WORKDIR /app

RUN addgroup --system pygroup && adduser --system --ingroup pygroup pyuser

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

RUN chown -R pyuser:pygroup /app

USER pyuser