FROM python:3.11-slim

WORKDIR /app

RUN addgroup --system pygroup && adduser --system --ingroup pygroup pyuser

COPY ./app /app/app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

RUN chown -R pyuser:pygroup /app

USER pyuser

CMD [ "uvicorn", "app.main:app", "--host 0.0.0.0", "--port 8000" ]