name: Container Security Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read
  packages: read

jobs:
  trivy-scan:
    name: Trivy CVE Scanner
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image (no push)
        uses: docker/build-push-actions@v5
        with:
          context: .
          load: true
          tags: falcon-api:${{ github.sha }}

      - name: Run Trivy CVE scanner
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: falcon-api:${{ github.sha }}
          format: table
          output: reports/trivy-report.txt
          severity: CRITICAL,HIGH

  
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-actions@v3.1.0
        with:
          dockerfile: ./Dockerfile
